-- MySQL Script generated by MySQL Workbench
-- Sun Jan 26 22:16:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cuadros-DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cuadros-DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cuadros-DB` DEFAULT CHARACTER SET utf8 ;
USE `Cuadros-DB` ;

-- -----------------------------------------------------
-- Table `Cuadros-DB`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cuadros-DB`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`, `apellido`),
  UNIQUE INDEX `idAutor_UNIQUE` (`idAutor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cuadros-DB`.`Cuadro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cuadros-DB`.`Cuadro` (
  `idCuadros` INT NOT NULL,
  `precio` DECIMAL NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idCuadros`, `Autor_idAutor`),
  UNIQUE INDEX `idCuadros_UNIQUE` (`idCuadros` ASC) VISIBLE,
  INDEX `fk_Cuadros_Autor_idx` (`Autor_idAutor` ASC) VISIBLE,
  UNIQUE INDEX `Autor_idAutor_UNIQUE` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Cuadros_Autor`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `Cuadros-DB`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cuadros-DB`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cuadros-DB`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `Cuadros_idCuadros` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `apellido`, `dni`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `fk_Cliente_Cuadros1_idx` (`Cuadros_idCuadros` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cuadros1`
    FOREIGN KEY (`Cuadros_idCuadros`)
    REFERENCES `Cuadros-DB`.`Cuadro` (`idCuadros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
