-- MySQL Script generated by MySQL Workbench
-- Sun Jan 26 22:26:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RedSocial-DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RedSocial-DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RedSocial-DB` DEFAULT CHARACTER SET utf8 ;
USE `RedSocial-DB` ;

-- -----------------------------------------------------
-- Table `RedSocial-DB`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial-DB`.`Cliente` (
  `Cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `dni` VARCHAR(10) NOT NULL,
  `table1_idCuadro` INT NOT NULL,
  PRIMARY KEY (`Cliente`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `Cliente_UNIQUE` (`Cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial-DB`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial-DB`.`Video` (
  `idVideo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL,
  `titulo` VARCHAR(40) NULL,
  `url` VARCHAR(100) CHARACTER SET 'DEFAULT' GENERATED ALWAYS AS (https://www.youtube.com/),
  PRIMARY KEY (`idVideo`),
  UNIQUE INDEX `idVideo_UNIQUE` (`idVideo` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial-DB`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial-DB`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `obras` VARCHAR(45) NULL,
  `Libros_idLibro` INT NOT NULL,
  PRIMARY KEY (`idAutor`),
  UNIQUE INDEX `idAutor_UNIQUE` (`idAutor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial-DB`.`Amigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial-DB`.`Amigo` (
  `trabajo` INT NOT NULL,
  `ocio` VARCHAR(45) NULL,
  `internet` VARCHAR(45) NULL,
  `otros` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `idAmigo` INT NOT NULL,
  INDEX `fk_Amigo_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  PRIMARY KEY (`idAmigo`),
  UNIQUE INDEX `idAmigo_UNIQUE` (`idAmigo` ASC) VISIBLE,
  CONSTRAINT `fk_Amigo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `RedSocial-DB`.`UsuarioRS` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial-DB`.`UsuarioRS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial-DB`.`UsuarioRS` (
  `idUsuario` INT GENERATED ALWAYS AS (),
  `nombre` VARCHAR(20) NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `Fotos_idfotos` INT NULL,
  `Amigo_idAmigo` INT NOT NULL,
  `Video_idVideo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) VISIBLE,
  INDEX `fk_Usuario_Amigo1_idx` (`Amigo_idAmigo` ASC) VISIBLE,
  INDEX `fk_UsuarioRS_Video1_idx` (`Video_idVideo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Amigo1`
    FOREIGN KEY (`Amigo_idAmigo`)
    REFERENCES `RedSocial-DB`.`Amigo` (`idAmigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioRS_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `RedSocial-DB`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
