-- MySQL Script generated by MySQL Workbench
-- Sun Jan 26 22:20:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Stube-DB
-- -----------------------------------------------------
-- base de dates para You Tube

-- -----------------------------------------------------
-- Schema Stube-DB
--
-- base de dates para You Tube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Stube-DB` DEFAULT CHARACTER SET utf8 ;
USE `Stube-DB` ;

-- -----------------------------------------------------
-- Table `Stube-DB`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube-DB`.`Video` (
  `idVideo` INT NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idVideo`),
  UNIQUE INDEX `idVideo_UNIQUE` (`idVideo` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  INDEX `fk_Video_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Video_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Stube-DB`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stube-DB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube-DB`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `Video_idVideo` INT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) VISIBLE,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Video_idx` (`Video_idVideo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Video`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `Stube-DB`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
