-- MySQL Script generated by MySQL Workbench
-- Sun Jan 26 22:14:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Vueling
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Vueling
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vueling` DEFAULT CHARACTER SET utf8 ;
USE `Vueling` ;

-- -----------------------------------------------------
-- Table `Vueling`.`Plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Plane` (
  `idPlane` INT NULL,
  PRIMARY KEY (`idPlane`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Seat` (
  `idSeat` INT NOT NULL,
  `Plane_idPlane` INT NOT NULL,
  PRIMARY KEY (`idSeat`),
  INDEX `fk_Seat_Plane_idx` (`Plane_idPlane` ASC) VISIBLE,
  CONSTRAINT `fk_Seat_Plane`
    FOREIGN KEY (`Plane_idPlane`)
    REFERENCES `Vueling`.`Plane` (`idPlane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `obras` VARCHAR(45) NULL,
  `Libros_idLibro` INT NOT NULL,
  PRIMARY KEY (`idAutor`),
  UNIQUE INDEX `idAutor_UNIQUE` (`idAutor` ASC) VISIBLE,
  INDEX `fk_Autor_Libros1_idx` (`Libros_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_Libros1`
    FOREIGN KEY (`Libros_idLibro`)
    REFERENCES `Vueling`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Cuadros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Cuadros` (
  `idCuadro` INT GENERATED ALWAYS AS (),
  `precio` VARCHAR(5) NULL,
  `table2_idAutor` INT NULL,
  PRIMARY KEY (`idCuadro`),
  UNIQUE INDEX `idQuadre_UNIQUE` (`idCuadro` ASC) VISIBLE,
  INDEX `fk_table1_table21_idx` (`table2_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_table1_table21`
    FOREIGN KEY (`table2_idAutor`)
    REFERENCES `Vueling`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Cliente` (
  `idCliente` INT GENERATED ALWAYS AS (),
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(45) NULL,
  `puerta` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `fecha registro` VARCHAR(45) NOT NULL,
  `recomendado por` VARCHAR(45) NULL,
  `Gafas_idGafa` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  INDEX `fk_Cliente_Gafas1_idx` (`Gafas_idGafa` ASC) VISIBLE,
  CONSTRAINT `recomendado por`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Vueling`.`Cliente` (`Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Gafas1`
    FOREIGN KEY (`Gafas_idGafa`)
    REFERENCES `Vueling`.`Gafas` (`idGafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Video` (
  `idVideo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL,
  `titulo` VARCHAR(40) NULL,
  `url` VARCHAR(100) CHARACTER SET 'DEFAULT' GENERATED ALWAYS AS (https://www.youtube.com/),
  PRIMARY KEY (`idVideo`),
  UNIQUE INDEX `idVideo_UNIQUE` (`idVideo` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `Video_idVideo` INT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Usuarios_Video1_idx` (`Video_idVideo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `Vueling`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `obras` VARCHAR(45) NULL,
  `Libros_idLibro` INT NOT NULL,
  PRIMARY KEY (`idAutor`),
  UNIQUE INDEX `idAutor_UNIQUE` (`idAutor` ASC) VISIBLE,
  INDEX `fk_Autor_Libros1_idx` (`Libros_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_Libros1`
    FOREIGN KEY (`Libros_idLibro`)
    REFERENCES `Vueling`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Libros` (
  `idLibro` INT GENERATED ALWAYS AS (),
  `stock` VARCHAR(5) NULL,
  `precio` VARCHAR(4) NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idLibro`),
  UNIQUE INDEX `idLibro_UNIQUE` (`idLibro` ASC) VISIBLE,
  INDEX `fk_Libros_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `Vueling`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Libros_idLibro` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `total` VARCHAR(5) NULL,
  PRIMARY KEY (`idVenta`),
  UNIQUE INDEX `idVenta_UNIQUE` (`idVenta` ASC) VISIBLE,
  INDEX `fk_Ventas_Libros1_idx` (`Libros_idLibro` ASC) VISIBLE,
  INDEX `fk_Ventas_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Libros1`
    FOREIGN KEY (`Libros_idLibro`)
    REFERENCES `Vueling`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Vueling`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Usuario` (
  `idUsuario` INT GENERATED ALWAYS AS (),
  `nombre` VARCHAR(20) NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `Fotos_idfotos` INT NULL,
  `Amigo_idAmigo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) VISIBLE,
  INDEX `fk_Usuario_Fotos1_idx` (`Fotos_idfotos` ASC) VISIBLE,
  INDEX `fk_Usuario_Amigo1_idx` (`Amigo_idAmigo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Fotos1`
    FOREIGN KEY (`Fotos_idfotos`)
    REFERENCES `Vueling`.`Fotos` (`idfotos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Amigo1`
    FOREIGN KEY (`Amigo_idAmigo`)
    REFERENCES `Vueling`.`Amigo` (`idAmigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Fotos` (
  `idfotos` INT GENERATED ALWAYS AS (),
  `direcion` VARCHAR(45) NULL,
  `url` VARCHAR(45) GENERATED ALWAYS AS (),
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idfotos`),
  UNIQUE INDEX `idfotos_UNIQUE` (`idfotos` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  INDEX `fk_fotos_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Vueling`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Amigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Amigo` (
  `trabajo` INT NOT NULL,
  `ocio` VARCHAR(45) NULL,
  `internet` VARCHAR(45) NULL,
  `otros` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `idAmigo` INT NOT NULL,
  INDEX `fk_Amigo_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  PRIMARY KEY (`idAmigo`),
  UNIQUE INDEX `idAmigo_UNIQUE` (`idAmigo` ASC) VISIBLE,
  CONSTRAINT `fk_Amigo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Vueling`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Usuario` (
  `idUsuario` INT GENERATED ALWAYS AS (),
  `nombre` VARCHAR(20) NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `Fotos_idfotos` INT NULL,
  `Amigo_idAmigo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) VISIBLE,
  INDEX `fk_Usuario_Fotos1_idx` (`Fotos_idfotos` ASC) VISIBLE,
  INDEX `fk_Usuario_Amigo1_idx` (`Amigo_idAmigo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Fotos1`
    FOREIGN KEY (`Fotos_idfotos`)
    REFERENCES `Vueling`.`Fotos` (`idfotos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Amigo1`
    FOREIGN KEY (`Amigo_idAmigo`)
    REFERENCES `Vueling`.`Amigo` (`idAmigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Empleado` (
  `idEmpleado` INT GENERATED ALWAYS AS (),
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha inicio` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Gafas` (
  `idGafa` INT GENERATED ALWAYS AS (),
  `marca` VARCHAR(45) NULL,
  `graduacion1` VARCHAR(45) NULL,
  `graduacion2` VARCHAR(45) NULL,
  `montura` VARCHAR(45) NULL,
  `color montura` VARCHAR(45) NULL,
  `color vidrio` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `Proveedor_idProveedor` INT UNSIGNED NOT NULL,
  `Empleado_idEmpleado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idGafa`),
  UNIQUE INDEX `idGafas_UNIQUE` (`idGafa` ASC) VISIBLE,
  INDEX `fk_Gafas_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  INDEX `fk_Gafas_Empleado1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Gafas_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `Vueling`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gafas_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Vueling`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Proveedor` (
  `idProveedor` INT GENERATED ALWAYS AS (),
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(45) NULL,
  `puerta` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NOT NULL,
  `Gafas_idGafa` INT NOT NULL,
  PRIMARY KEY (`idProveedor`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  INDEX `fk_Proveedor_Gafas1_idx` (`Gafas_idGafa` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_Gafas1`
    FOREIGN KEY (`Gafas_idGafa`)
    REFERENCES `Vueling`.`Gafas` (`idGafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling`.`Cliente` (
  `idCliente` INT GENERATED ALWAYS AS (),
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(45) NULL,
  `puerta` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `fecha registro` VARCHAR(45) NOT NULL,
  `recomendado por` VARCHAR(45) NULL,
  `Gafas_idGafa` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  INDEX `fk_Cliente_Gafas1_idx` (`Gafas_idGafa` ASC) VISIBLE,
  CONSTRAINT `recomendado por`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Vueling`.`Cliente` (`Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Gafas1`
    FOREIGN KEY (`Gafas_idGafa`)
    REFERENCES `Vueling`.`Gafas` (`idGafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
