-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 13:36:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Amazon-DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Amazon-DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Amazon-DB` DEFAULT CHARACTER SET utf8 ;
USE `Amazon-DB` ;

-- -----------------------------------------------------
-- Table `Amazon-DB`.`AutorAmazon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon-DB`.`AutorAmazon` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `obras` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon-DB`.`LibrosAmazon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon-DB`.`LibrosAmazon` (
  `idLibro` INT GENERATED ALWAYS AS (),
  `nombre` VARCHAR(255) NULL,
  `stock` VARCHAR(5) NULL,
  `precio` DECIMAL(5) NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idLibro`),
  INDEX `fk_Libros_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `Amazon-DB`.`AutorAmazon` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon-DB`.`VentasAmazon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon-DB`.`VentasAmazon` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Libros_idLibro` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `total` DECIMAL(5) NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Ventas_Libros1_idx` (`Libros_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Libros1`
    FOREIGN KEY (`Libros_idLibro`)
    REFERENCES `Amazon-DB`.`LibrosAmazon` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon-DB`.`UsuarioAmazon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon-DB`.`UsuarioAmazon` (
  `idUsuario` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Ventas_idVenta` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Ventas1_idx` (`Ventas_idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Ventas1`
    FOREIGN KEY (`Ventas_idVenta`)
    REFERENCES `Amazon-DB`.`VentasAmazon` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
