-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 13:22:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Vueling-DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Vueling-DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vueling-DB` DEFAULT CHARACTER SET utf8 ;
USE `Vueling-DB` ;

-- -----------------------------------------------------
-- Table `Vueling-DB`.`Plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling-DB`.`Plane` (
  `idPlane` INT NOT NULL,
  PRIMARY KEY (`idPlane`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vueling-DB`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vueling-DB`.`Seat` (
  `idSeat` INT NOT NULL,
  `Plane_idPlane` INT NOT NULL,
  PRIMARY KEY (`idSeat`),
  INDEX `fk_Seat_Plane_idx` (`Plane_idPlane` ASC) VISIBLE,
  CONSTRAINT `fk_Seat_Plane`
    FOREIGN KEY (`Plane_idPlane`)
    REFERENCES `Vueling-DB`.`Plane` (`idPlane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
